# Generated by Django 4.2.4 on 2023-08-24 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_pages_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='ref_categoryPage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.categorypage'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pages',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pages.categorypage'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='url',
            field=models.URLField(),
        ),
    ]
